package main

import (
	"fmt"
	"net/http"
	"strings"
)

func main() {
	// ルーティング設定
	http.HandleFunc("/", memo)
	http.HandleFunc("/download", download)

	fmt.Println("Server running at http://localhost:8080")
	// サーバー起動とエラーハンドリング
	if err := http.ListenAndServe(":8080", nil); err != nil {
		fmt.Printf("Server failed to start: %v\n", err)
	}
}

// 入力画面（HTML）を表示する関数
func memo(w http.ResponseWriter, r *http.Request) {
	s := `
<html>
<head>
<meta charset="UTF-8">
<title>メモ保存アプリ</title>
<style>
	body { font-family: sans-serif; margin:40px; background-color: #f4f4f9; color: #333; }
	.container { max-width: 600px; margin: auto; background: white; padding: 25px; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); }
	h2 { text-align: center; color: #007bff; }
	label { font-weight: bold; display: block; margin-bottom: 5px; }
	textarea { width:100%; height:200px; margin-bottom: 20px; padding: 12px; border: 1px solid #ccc; border-radius: 6px; resize: vertical; box-sizing: border-box; }
	select, input[type="text"] { padding:10px; width: 100%; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 6px; box-sizing: border-box; }
	input[type="submit"] { background: #007bff; color: white; border: none; padding: 12px 20px; border-radius: 6px; cursor: pointer; width: 100%; font-size: 16px; transition: background 0.3s; }
	input[type="submit"]:hover { background: #0056b3; }
</style>
</head>
<body>
<div class="container">
	<h2>📝 メモ保存アプリ</h2>
	<form method="post" action="/download">
		<label>ファイル名:</label>
		<input type="text" name="filename" placeholder="memo" value="memo">

		<label>保存形式:</label>
		<select name="type">
			<option value="txt">テキスト (.txt)</option>
			<option value="csv">CSV (.csv)</option>
			<option value="dat">データ (.dat)</option>
			<option value="html">HTML (.html)</option>
			<option value="cs">C# ソース (.cs)</option>
		</select>

		<label>メモ内容:</label>
		<textarea name="text" placeholder="ここにメモを入力してください..."></textarea>

		<input type="submit" value="ファイルを保存してダウンロード">
	</form>
</div>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Write([]byte(s))
}

// ダウンロード処理を行う関数
func download(w http.ResponseWriter, r *http.Request) {
	// 1. POSTメソッド以外を弾く（セキュリティ向上）
	if r.Method != http.MethodPost {
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
		return
	}

	// 2. フォームデータの解析
	if err := r.ParseForm(); err != nil {
		http.Error(w, "Bad Request", http.StatusBadRequest)
		return
	}

	name := r.FormValue("filename")
	typ := r.FormValue("type")
	text := r.FormValue("text")

	// ファイル名が空の場合はデフォルト名を設定
	if name == "" {
		name = "memo"
	}

	// 3. 各形式に合わせたデータ加工
	var content string
	var contentType string = "application/octet-stream; charset=utf-8"

	switch typ {
	case "txt":
		content = text
	case "csv":
		// Excelで開きやすいよう、ダブルクォートでエスケープ
		content = `"` + strings.ReplaceAll(text, `"`, `""`) + `"`
	case "dat":
		// データ形式としてヘッダーを付与
		content = "--- DATA FILE ---\n" + text
	case "html":
		// ブラウザで直接開いても文字化けしないHTML構造
		content = "<!DOCTYPE html><html><head><meta charset='utf-8'></head><body><pre>" + text + "</pre></body></html>"
		contentType = "text/html; charset=utf-8"
	case "cs":
		// C#ソースコード形式に整える
		content = fmt.Sprintf("/* Generated by Go App */\nusing System;\n\npublic class Memo {\n    public static void Main() {\n        Console.WriteLine(@\"%s\");\n    }\n}", strings.ReplaceAll(text, `"`, `""`))
	default:
		// 想定外の形式に対するエラー処理
		http.Error(w, "Invalid Format", http.StatusBadRequest)
		return
	}

	// 4. ダウンロード用ヘッダーの設定
	filename := fmt.Sprintf("%s.%s", name, typ)
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	w.Header().Set("Content-Type", contentType)


	bom := []byte{0xEF, 0xBB, 0xBF}
	if _, err := w.Write(bom); err != nil {
		fmt.Printf("BOM Error: %v\n", err)
		return
	}

	// 6. メモ本体の書き込み
	if _, err := w.Write([]byte(content)); err != nil {
		fmt.Printf("Write Error: %v\n", err)
	}
}
